run_dir: 'run_dir'
staging_dir: 'staging_dir'
results_dir: 'results_dir'
decompression_dir: 'decompression_dir'
archive_dir: 'archive_dir'
mountpoint_dir: 'mountpoint_dir'

sequencing_dirs:
  - run_dir1
  - run_dir2
#  - /07_Oncoservice/Runs
#  - /08_Projekte/CBmed/Runs

ready_tags:
  - SequenceComplete.txt
  - CopyComplete.txt
  - RTAComplete.txt

blocking_tags:
  - ANALYZED.txt
  - ANALYSIS_FAILED.txt
  - FAILED.txt
  - IGNORED.txt

status_tags:
  - Analyzing.txt
  - ARCHIVING.txt
  - DECOMPRESSING.txt

samplesheet: 'SampleSheet.csv'
mountpoint_binary: '/usr/bin/mountpoint'

rules_sequence:
  - check_mountpoint
  - check_structure
  - check_docker_image

# Useful stuff
#ready_tags = [
#    "SequenceComplete.txt",
#    "CopyComplete.txt",
#    "RTAComplete.txt"
#]
#
#blocking_tags = [
#    "ANALYZED.txt",
#    "ANALYSIS_FAILED.txt",
#    "FAILED.txt",
#    "IGNORED.txt"
#]
#
#status_tags = [
#    "Analyzing.txt",
#    "ARCHIVING.txt",
#    "DECOMPRESSING.txt"
#]