testing_fast: False
pipeline_dir: '/mnt/Novaseq/TSO_pipeline'
test_runs_dir: '/mnt/Novaseq/TSO_pipeline/test_runs'
staging_temp_dir: '/staging/tmp'
server_availability_dir: '/mnt/NovaseqXplus/TSO_pipeline/server_availability'
oncoservice_sequencing_dir: '/mnt/NovaseqXplus/07_Oncoservice'
oncoservice_novaseqx_dir: '/mnt/NovaseqXplus/07_Oncoservice'
oncoservice_novaseq6000_dir: '/mnt/Novaseq/07_Oncoservice'
cbmed_novaseq_dir: '/mnt/Novaseq/08_Projekte/CBmed'
oncoservice_dir: '/mnt/NovaseqXplus/07_Oncoservice'
cbmed_sequencing_dir: '/mnt/CBmed_NAS3/Genomics/TSO500_liquid'
cbmed_nsq6000_dir: '/mnt/Novaseq/08_Projekte/CBmed/Runs'
cbmed_nsqx_dir: '/mnt/NovaseqXplus/08_Projekte/CBmed'
# TODO Change in prod
cbmed_results_dir: '/mnt/CBmed/Genomics/TSO500_liquid'
mixed_runs_dir: '/mnt/NovaseqXplus/10_MixedRuns'
patho_seq_dir: '/mnt/Patho/TSO500_NovaSeq6000'
patho_sequencing_dir: '/mnt/Patho/TSO500_NovaSeq6000'
# cbmed_results_dir: '/mnt/CBmed_NAS3/Genomics/TSO500_liquid'
patho_dir: '/mnt/Patho/TSO500_DRAGEN'
patho_results_dir: '/mnt/Patho/TSO500_DRAGEN'
sx182_mountpoint: '/mnt/Novaseq/'
sy176_mountpoint: '/mnt/NovaseqXplus'
# TODO Change in prod
logging_dir: '/mnt/Novaseq/TSO_pipeline/01_Staging/pure-python-refactor/logs'
research_dir: '/mnt/NovaseqXplus/02_HuGe_Forschung'
research_sequencing_dir: '/mnt/NovaseqXplus/02_HuGe_Forschung/Runs'
archive_dir: '/mnt/NovaseqXplus/HuGe_Diagnostik-ARCHIV'
reanalysis_dir: '/mnt/NovaseqXplus/06_Reanalyse'


ready_tags:
  - SequenceComplete.txt
  - CopyComplete.txt
  - RTAComplete.txt

ready_tags_nsqx:
  - CopyComplete.txt
  - RTAComplete.txt

blocking_tags:
  - ANALYZED.txt
  - FAILED.txt
  - PENDING.txt
  - ANALYZING.txt
  - QUEUED.txt

blocking_tags_validator:
  - ANALYZED.txt
  - FAILED.txt
  - PENDING.txt
  - ANALYZING.txt
  - QUEUED.txt
  - ARCHIVING.txt
  - ARCHIVED.txt

status_tags:
  - Analyzing.txt
  - ARCHIVING.txt

available_servers:
  - 10.200.214.104
  - 10.200.215.35

tags:
  - TSO
  - CBM
  - ONC

pending_tag: PENDING.txt
queued_tag: QUEUED.txt
analyzed_tag: ANALYZED.txt
analyzing_tag: ANALYZING.txt
archiving_tag: ARCHIVING.txt
archived_tag: ARCHIVED.txt
archiving_failed_tag: ARCHIVING_FAILED.txt
reanalysis_failed_tag: REANALYSIS_FAILED.txt
server_idle_tag: IDLE.txt
failed_tag: FAILED.txt
server_busy_tag: BUSY.txt
samplesheet: 'SampleSheet.csv'
mountpoint_binary: '/usr/bin/mountpoint'

error_messages:
  1: "No or invalid options passed - general error"
  5: "Needs either --runFolder or --fastqFolder"
  6: "An input folder is not a directory, does not exist, or has wrong permissions"
  7: "Specified config file does not exist"
  8: "Mount permissions fastq_dirion errors on docker - try not using a network mount"
  9: "DRAGEN is not installed or wrong DRAGEN version is installed"
  10: "Attempt to run without a runFolder"
  11: "Not enough available disk space for analysis output"
  12: "Existing DRAGEN process or workflow docker container running"
  13: "Missing CopyComplete.txt file in run folder"
  14: "User can't run docker"
  15: "Invalid/expired/missing DRAGEN license"
  16: "Passed wrong combination of runFolder and fastqFolder"

# Samplesheet requirements
expected_headers_nsqx: &expected_headers_nsqx
  - "[Header],\n"
  - "[Reads]\n"
  - "[Sequencing_Settings]\n"
  - "[BCLConvert_Settings]\n"
  - "[TSO500L_Settings]\n"
  - "[TSO500L_Data]\n"

# Run name is variable (kept out of the list on purpose)
expected_header_section_nsqx: &expected_header_section_nsqx
  - "FileFormatVersion,2\n"
  - "InstrumentPlatform,NovaSeqXSeries\n"
  - "IndexOrientation,Forward\n"
  - "\n"

expected_read_section_nsqx: &expected_read_section_nsqx
  - "Read1Cycles,151\n"
  - "Read2Cycles,151\n"
  - "Index1Cycles,10\n"
  - "Index2Cycles,10\n"
  - "\n"

expected_seq_settings_section_nsqx: &expected_seq_settings_section_nsqx
  - "LibraryPrepKits,TSO500ctDNA_v2\n"
  - "\n"

expected_bcl_settings_section_nsqx: &expected_bcl_settings_section_nsqx
  - "SoftwareVersion,2.1.1\n"
  - "AdapterRead1,CTGTCTCTTATACACATCT\n"
  - "AdapterRead2,CTGTCTCTTATACACATCT\n"
  - "OverrideCycles,U7N1Y143;I10;I10;U7N1Y143\n"
  - "MaskShortReads,35\n"
  - "AdapterBehavior,trim\n"
  - "MinimumTrimmedReadLength,35\n"
  - "FastqCompressionFormat,gzip\n"
  - "\n"

expected_tso500_settings_section_nsqx: &expected_tso500_settings_section_nsqx
  - "SoftwareVersion,2.1.1\n"
  - "StartsFromFastq,false\n"
  - "\n"

expected_sections_nsqx:
  "[Header],\n": *expected_header_section_nsqx
  "[Reads]\n": *expected_read_section_nsqx
  "[Sequencing_Settings]\n": *expected_seq_settings_section_nsqx
  "[BCLConvert_Settings]\n": *expected_bcl_settings_section_nsqx
  "[TSO500L_Settings]\n": *expected_tso500_settings_section_nsqx


expected_headers_nsq6000: &expected_headers_nsq6000
  - "[Header],,,,\n"
  - "[Reads],,,,\n"
  - "[Sequencing_Settings],,,,\n"
  - "[BCLConvert_Settings],,,,\n"
  - "[BCLConvert_Data],,,,\n"
  - "[TSO500L_Settings],,,,\n"
  - "[TSO500L_Data],,,,\n"

expected_header_section_nsq6000: &expected_header_section_nsq6000
  - "FileFormatVersion,2,,,\n"
  - "InstrumentPlatform,NovaSeq,,,\n"
  - "IndexOrientation,Forward,,,\n"

expected_read_section_nsq6000: &expected_read_section_nsq6000
  - "Read1Cycles,151,,,\n"
  - "Read2Cycles,151,,,\n"
  - "Index1Cycles,10,,,\n"
  - "Index2Cycles,10,,,\n"

expected_seq_settings_section_nsq6000: &expected_seq_settings_section_nsq6000
  - "LibraryPrepKits,TSO500ctDNA_v2,,,\n"

expected_bcl_settings_section_nsq6000: &expected_bcl_settings_section_nsq6000
  - "SoftwareVersion,02.01.2001,,,\n"
  - "AdapterRead1,CTGTCTCTTATACACATCT,,,\n"
  - "AdapterRead2,CTGTCTCTTATACACATCT,,,\n"
  - "MaskShortReads,35,,,\n"
  - "OverrideCycles,U7N1Y143,I10,I10,U7N1Y143\n"
  - "AdapterBehavior,trim,,,\n"
  - "MinimumTrimmedReadLength,35,,,\n"

expected_tso500_settings_section_nsq6000: &expected_tso500_settings_section_nsq6000
  - "SoftwareVersion,02.01.2001,,,\n"
  - "StartsFromFastq,0,,,\n"

expected_sections_nsq6000:
  "[Header],,,,\n": *expected_header_section_nsq6000
  "[Reads],,,,\n": *expected_read_section_nsq6000
  "[Sequencing_Settings],,,,\n": *expected_seq_settings_section_nsq6000
  "[BCLConvert_Settings],,,,\n": *expected_bcl_settings_section_nsq6000
  "[TSO500L_Settings],,,,\n": *expected_tso500_settings_section_nsq6000
