# TODO Change in prod
pipeline_dir: '/mnt/Novaseq/TSO_pipeline/02_Development'
staging_dir: '/staging'
server_availability_dir: '/mnt/Novaseq/TSO_pipeline/server_availability'
oncoservice_dir: '/mnt/Novaseq/07_Oncoservice'
cbmed_dir: '/mnt/Novaseq/08_Projekte/CBmed'
novaseq_mountpoint: '/mnt/Novaseq'
# TODO Change in prod
logging_dir: '/mnt/Novaseq/TSO_pipeline/02_Development/logs'

ready_tags:
  - SequenceComplete.txt
  - CopyComplete.txt
  - RTAComplete.txt

blocking_tags:
  - ANALYZED.txt
  - FAILED.txt
  - IGNORED.txt

status_tags:
  - Analyzing.txt
  - ARCHIVING.txt

pending_run_tag: PENDING_RUN.txt
server_idle_tag: IDLE.txt
server_busy_tag: BUSY.txt

samplesheet: 'SampleSheet.csv'
mountpoint_binary: '/usr/bin/mountpoint'

rules_sequence:
  - check_mountpoint
  - check_structure
  - check_docker_image

# Useful stuff
#ready_tags = [
#    "SequenceComplete.txt",
#    "CopyComplete.txt",
#    "RTAComplete.txt"
#]
#
#blocking_tags = [
#    "ANALYZED.txt",
#    "ANALYSIS_FAILED.txt",
#    "FAILED.txt",
#    "IGNORED.txt"
#]
#
#status_tags = [
#    "Analyzing.txt",
#    "ARCHIVING.txt",
#    "DECOMPRESSING.txt"
#]